### ISSUE TITLE
Time Zone issue...

### ISSUE THREAD

**Issue by GCM2021** [KonstantinPankratov/WordPress-Plugin-Date-counter#3]
I live in Central Standard time zone in North America.  However, it is 6 pm on 2-6-2021, but when I use the "currentDay" format, it is already populating as tomorrow, 2-7-2021, although it's not even midnight yet.  I went and fixed my time zone under general settings in WordPress, and then went back to refresh the page where I'm using the code, updated, and still it is giving the same results.  How do I specifically adjust the time zone that this plug-in uses to calculate results?

**Comment by KonstantinPankratov** [comment]
Hey, time zone support was added!
